/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Aiways } from "./Aiways";
export type { Erc20 } from "./Erc20";
export * as factories from "./factories";
export { Aiways__factory } from "./factories/Aiways__factory";
export { Erc20__factory } from "./factories/Erc20__factory";
